id: I2F49926E
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T09:18:35.296719'
last_modified: '2022-06-19T09:18:35.296732'
parser: null
source_metadata:
  title: Autobiography of rMor chen Kun dga lhun grub (1654–1726/28); Lamdre Lobshe,
    vol. ca, title no. 4
  author: རྨོར་ཆེན་ཀུན་དགའ་ལྷུན་གྲུབ།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2013-09-04);
    unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:རྫོང་སར་ཁམས་བྱེའི་ལྔ་རིག་སློབ་གླིང་། སྡེ་དགེ་རྫོང་སར། (dzkj)
  - Editorial process:Mathias Fermer (mf), ཀུན་དགའ་རྡོ་རྗེ། (Kathmandu) (kun)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/264
  bases:
    ad42:
      title: Autobiography of rMor chen Kun dga lhun grub (1654–1726/28); Lamdre Lobshe,
        vol. ca, title no. 4
      order: 1
      base_file: ad42.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
